# Generated by Django 3.1.1 on 2021-11-25 13:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_student_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, default=2, max_length=500, verbose_name='Students history'),
            preserve_default=False,
        ),
    ]
